<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE family [
<!ELEMENT family (people, machine)>
<!ELEMENT people (name, sex, age, taste)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT taste (#PCDATA)>

<!ELEMENT machine (name, count, detail)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT count (#PCDATA)>
<!ELEMENT detail (#PCDATA)>
]>
<family>
	<people>
		<name>stan</name>
		<sex>male</sex>
		<age>28</age>
		<taste>ddddd</taste>
	</people>
	<mechine>
		<name>cooler</name>
		<count>1</count>
		<detail>ffrf</detail>
	</mechine>
</family>