=== Talend/tuj/tuj/java/Bug2927_XSD_Output/out.xsd
<?xml version="1.0" encoding="ISO-8859-15"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="rootTag" nillable="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="aaa" nillable="true" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="bbb" nillable="true" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="ccc" nillable="true" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="rrr" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="ddd" nillable="true" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="eee" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
                          <xsd:element name="ggg" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
                          <xsd:element name="hhh" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
                          <xsd:element name="jjjj" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                        <xsd:attribute name="fff"/>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Talend/tuj/tuj/java/XML/Bug3197_NullModeGeneration_xsd/out.xml
<?xml version="1.0" encoding="ISO-8859-15"?>

<rootTag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation= "out.xsd">
  <aaa>
    <bbb>
      <ddd fff="good">
        <eee>good</eee>
        <ggg>defaultValue</ggg>
        <hhh>2</hhh>
        <jjjj xsi:nil="true"></jjjj>
      </ddd>
      <ddd fff="good">
        <eee>good</eee>
        <ggg>defaultValue</ggg>
        <hhh>2</hhh>
        <jjjj xsi:nil="true"></jjjj>
      </ddd>
      <ddd fff="good">
        <eee>good</eee>
        <ggg>defaultValue</ggg>
        <hhh>2</hhh>
        <jjjj xsi:nil="true"></jjjj>
      </ddd>
      <ddd fff="good">
        <eee>good</eee>
        <ggg>defaultValue</ggg>
        <hhh>2</hhh>
        <jjjj xsi:nil="true"></jjjj>
      </ddd>
      <ddd fff="good">
        <eee>good</eee>
        <ggg>defaultValue</ggg>
        <hhh>2</hhh>
        <jjjj xsi:nil="true"></jjjj>
      </ddd>
    </bbb>
  </aaa>
</rootTag>
